#!/usr/bin/perl -w
#
# OpenRADIUS module that de/encapsulates RADIUS Class attributes contents.
#
# Usage: radclasspacker [-d] -o|-i
# 
# When running with -i option, the module encodes and packs all
# instances of Class attributes found in request chain and
# encodes them into a proprietary form. The result is then put
# into an 'str' attribute on response chain.
#
# When running with -o option, the module uses the value of the last
# 'str' attribute from incoming request chain as an encoded set of
# Class attributes values, decodes them and puts them into response chain.
#
# Class attributes relative ordering is preserved.
#
# Author: Ilya Etingof <elie@rol.ru>, 2008
#
# This code has been derived from Emile van Bergen's radsql module.
#
# Permission to redistribute an original or modified version of this program in
# source, intermediate or object code form is hereby granted exclusively under
# the terms of the GNU General Public License, version 2. Please see the file
# COPYING for details, or refer to http://www.gnu.org/copyleft/gpl.html.
#


########
# USES #
########

use Getopt::Long;
use strict qw(vars);
use POSIX qw(asctime);
use MIME::Base64;
use Time::HiRes qw(time);

###########
# OPTIONS #
###########

my $progid = "radclasspacker";
my $pid = "[" . $$ . "]";
my $usage = 0;
my $debug = 0;
my $encode = 0;
my $decode = 0;
my $str;
my $stat_file;
my $stat_interval = 5;

########
# MAIN #
########

# Get options

Getopt::Long::Configure("bundling");
GetOptions("h"  => \$usage,
           "d" => \$debug,
           "i" => \$encode,
           "o" => \$decode,
           "s=s" => \$stat_file,
           "I=i" => \$stat_interval,
           "interval=i" => \$stat_interval);

if ($usage || !($encode ^ $decode)) {
    die("Usage: $progid [-d] -i|-o\n" .
        "       $progid -h\n" .
        "Where:\n" .
        "       -i -- pack Class attributes into a single str\n" .
        "       -o -- unpack str into a set of Class attributes\n" .
        "       -s -- stats output file\n" .
        "       -I -- stats interval minutes (default 5)\n");
}

# Check that we're running under OpenRADIUS, interface version 1

unless ($debug ||
    $ENV{'RADIUSINTERFACEVERSION'} &&
    $ENV{'RADIUSINTERFACEVERSION'} == 1) {
    die "not running under OpenRADIUS, interface v1!\n";
}

# Set record separator to empty line and loop on input.

$/ = "\n\n";
$| = 1;         # Important - we're outputting to a pipe

my $stats_lib = $0;
$stats_lib =~ s{/[^/]+$}{};
require "$stats_lib/../stats.pl";
stats_init($progid, $stat_file, $stat_interval);

if ($debug) {
    print STDERR "$progid$pid: mode is ", $encode ? "encode\n" : "decode\n";
}

if ($encode) {
    while(<STDIN>) {
        my $start = time();
        $str = "";
        while(s/^\s*
              ([A-Za-z0-9:-]+)               # attribute ($1)
              \s*=\s*
              (
               (\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}).*|      # ip ($3)
               (\d+).*|                      # int or date ($4)
               \"([^\"]*)\".*|               # quoted str ($5)
               ([^\"].*)                     # bare str ($6)
               )
              (\n|\$)//mx
              )
        {
            if ($1 eq "Class") {
                if ($debug) {
                    print STDERR "$progid$pid: got Class = \"$5\"\n";
                }
                if ($str) {
                    $str = $str . "|";
                }
                $str = $str . encode_base64($5);
            }
        }
    
        if ($str) {
            $str =~ s/\n//g;
            if ($debug) {
                print STDERR "$progid$pid: return str=\"$str\"\n";
            }
            print "int=1\nstr=\"" . $str . "\"\n\n";
        } else {
            print "int=0\n\n";
        }
        my $elapsed_ms = int((time() - $start) * 1000);
        stats_record($elapsed_ms);
    }
}

if ($decode) {
    while(<STDIN>) {
        my $start = time();
        $str = "";
        while(s/^\s*
              ([A-Za-z0-9:-]+)               # attribute ($1)
              \s*=\s*
              (
               (\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}).*|      # ip ($3)
               (\d+).*|                      # int or date ($4)
               \"([^\"]*)\".*|               # quoted str ($5)
               ([^\"].*)                     # bare str ($6)
               )
              (\n|\$)//mx
              )
        {
            if ($1 eq "str") {
                if ($debug) {
                    print STDERR "$progid$pid: str=\"$5\"\n";
                }
                $str = $5;
                last;
            }
        }
    
        if (!$str) {
            print "int=0\n\n";
            last;
        }

        my @items = split(/\|/, $str);
        foreach my $item (@items) {
            $str = decode_base64($item . "\n");
            if ($debug) {
                print STDERR "$progid$pid: Class=\"$str\"\n";
            }
            print "Class=\"" . $str . "\"\n";
        }
        print "int=1\n\n";
        my $elapsed_ms = int((time() - $start) * 1000);
        stats_record($elapsed_ms);
    }
}

if ($debug) {
    print STDERR "$progid$pid: EOF from stdin\n";
}
