#!/bin/sh
#
# This file is in the public domain

# Process options - or how to do getopt(3) in shell scripts ;-)
DEBUG=0
SINGLE=0
USAGE=0
PIDFILE=
STATFILE=
STAT_INTERVAL_MIN=5
while [ -n "$1" ]	# Loop as long as $1 is nonempty
do
	case $1 in
		-d)
			DEBUG=1
			shift
			;;
		-o)
			# Used to redirect fd 2 (where debugging output
			# normally goes) to a file - same as server itself
			if [ ! "$2" = "" ]
			then
				exec 2>$2
				shift;
			else
				echo ERROR: Option -o requires an argument 1>&2
				USAGE=1
			fi
			shift
			;;
		-p)
			# Used to write pid into a file, for log rotation
			if [ ! "$2" = "" ]
			then
				PIDFILE=$2
				shift
			else
				echo ERROR: Option -p requires an argument
				USAGE=1
			fi
			shift
			;;
		-s)
			if [ ! "$2" = "" ]
			then
				STATFILE=$2
				shift
			else
				echo ERROR: Option -s requires an argument
				USAGE=1
			fi
			shift
			;;
		-i)
			if [ ! "$2" = "" ]
			then
				STAT_INTERVAL_MIN=$2
				shift
			else
				echo ERROR: Option -i requires an argument
				USAGE=1
			fi
			shift
			;;
		-h)
			USAGE=1
			shift
			;;
		*)
			# If this is not the last argument, it's an
			# unknown option - complain. Otherwise it's
			# the positional argument, and we're done
			# with the loop.
			if [ -n "$2" ] 	    # If $2 is nonempty, $1 is not last
			then
				echo ERROR: Unknown option $1 1>&2
				USAGE=1
				shift
			else
				break
			fi
			;;
	esac
done

if [ -z "$1" ]
then
	echo ERROR: No destination directory specified 1>&2
	USAGE=1
fi
DESTDIR=$1

if [ $USAGE = 1 ]
then
	echo "Usage: radacctlogger [-d][is][-o file][-p pidfile][-s statfile][-i minutes] destination-directory" 1>&2
	echo "       radacctlogger -h" 1>&2
	exit 1
fi

if [ -n "$PIDFILE" ]
then
	echo $$ >$PIDFILE
	trap "rm -f $PIDFILE; echo \"radacctlogger[$$]: mommy hates me\" 1>&2" TERM
fi

STATSDIR=$(dirname "$0")
. "$STATSDIR/../stats.sh"
stats_init "radacctlogger" "$STATFILE" "$STAT_INTERVAL_MIN"

# Loop, answering requests
while : 
do
	START_MS=$(stats_now_ms)
	# Read message
	OUTPUT=
	DATE=
        DESTFILE=$DESTDIR
	IFS='='
	while read ATR VAL && [ -n "$VAL" ]
	do
		IFS=' '
		if [ "str" = "$ATR" ]
		then
			# Remove quotes
			eval VAL=$VAL

			if [ -z "$DATE" ]; then
				DATE="$VAL"
			else
				# This should never happen
				if [ -z "$VAL" ]; then
					echo "radacctlogger[$$]: empty STR" 1>&2
					VAL="ASSHOLE"
				fi

				# Treat str's as subdirs
				DESTFILE="$DESTFILE/$VAL"
			fi
		else
			# Add pair. Note the real tab before $ATR
			OUTPUT="$OUTPUT	$ATR = $VAL
"
		fi
		IFS='='
	done
	IFS=' '

	# Show debugging output if requested
	[ $DEBUG = 1 ] && echo "radacctlogger[$$]: $OUTPUT" 1>&2

	if [ -z "$DATE" ]; then
		echo "radacctlogger[$$]: empty DATE, dropping $OUTPUT" 1>&2
		echo "int=1
"
		continue
	else
		# Add date header
		OUTPUT="$DATE
$OUTPUT"
	fi

	if [ ! -d $DESTFILE ]; then
		mkdir -p $DESTFILE
		if [ ! $? ]; then
			echo "radacctlogger[$$]: mkdir $DESTFILE failed" 1>&2
			echo "int=0
"
			continue
		fi
	fi

	DESTFILE="$DESTFILE/detail"

	# Log output to file
	echo "$OUTPUT" >> $DESTFILE
	if [ ! $? ]; then
		echo "radacctlogger[$$]: >> $DESTFILE failed" 1>&2
		echo "int=0
"
		continue
	fi

	# Reply
#	sleep 1		# testing only - don't worry, we're race-free ;-)
	echo "int=1
"

	END_MS=$(stats_now_ms)
	ELAPSED=$((END_MS - START_MS))
	stats_record "$ELAPSED"

done
